language: python
# Run these python versions:
python: ["3.4", "3.5", "3.6", "pypy"]

# Also run these python versions with a specific distribution:
matrix:
  include:
    - python: "3.4"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.4.7
    - python: "3.4"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.4"
      env: DJANGO_VERSION=1.9.13 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.4"
      env: DJANGO_VERSION=1.10.7 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.4"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.6.2
    - python: "3.4"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.4"
      env: DJANGO_VERSION=2.0.13 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.4"
      env: DJANGO_VERSION=2.0.13 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.5"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.4.7
    - python: "3.5"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.5"
      env: DJANGO_VERSION=1.9.13 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.5"
      env: DJANGO_VERSION=1.10.7 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.5"
      env: DJANGO_VERSION=1.11.2 REST_FRAMEWORK_VERSION=3.6.2
    - python: "3.5"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.5"
      env: DJANGO_VERSION=2.0.13 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.4.7
    - python: "3.6"
      env: DJANGO_VERSION=1.8.18 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.6"
      env: DJANGO_VERSION=1.9.13 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.6"
      env: DJANGO_VERSION=1.10.7 REST_FRAMEWORK_VERSION=3.5.3
    - python: "3.6"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.6.2
    - python: "3.6"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=1.11.9 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.6"
      env: DJANGO_VERSION=2.0.13 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=2.0.13 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.6"
      env: DJANGO_VERSION=2.1.15 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.6"
      env: DJANGO_VERSION=2.1.15 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.6"
      env: DJANGO_VERSION=2.2.8 REST_FRAMEWORK_VERSION=3.10.3
    - python: "3.6"
      env: DJANGO_VERSION=3.0.0 REST_FRAMEWORK_VERSION=3.10.3
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.0.13 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.0.13 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.1.15 REST_FRAMEWORK_VERSION=3.7.7
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.1.15 REST_FRAMEWORK_VERSION=3.8.2
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.2.8 REST_FRAMEWORK_VERSION=3.10.3
    - python: "3.7"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=3.0.0 REST_FRAMEWORK_VERSION=3.10.3
    - python: "3.8"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=2.2.8 REST_FRAMEWORK_VERSION=3.10.3
    - python: "3.8"
      dist: xenial
      sudo: required
      env: DJANGO_VERSION=3.0.0 REST_FRAMEWORK_VERSION=3.10.3

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="platform_purbeurre.settings"

services:
  - postgresql

script:
  - ./manage.py test purbeurre.tests