language: python
python:
  - '3'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="platform_purbeurre.settings"

services:
  - postgresql

script:
  - ./manage.py test purbeurre.tests