language: python
# Run these python versions:
python: ["3.5"]

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="platform_purbeurre.settings"

services:
  - postgresql

script:
  - pytest
