# Generated by Django 3.0.5 on 2020-04-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0002_auto_20200421_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryS0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat_s0', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryS1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat_s1', models.CharField(max_length=100)),
                ('name_cat_s0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.CategoryS0')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryS2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat_s2', models.CharField(max_length=100)),
                ('name_cat_s1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.CategoryS1')),
            ],
        ),
    ]
