# Generated by Django 3.0.5 on 2020-04-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0004_auto_20200428_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='purbeurre.Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='categorys1',
            name='name_cat_s0',
        ),
        migrations.DeleteModel(
            name='CategoryS0',
        ),
        migrations.DeleteModel(
            name='CategoryS1',
        ),
    ]
