# Generated by Django 3.0.5 on 2020-04-29 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0005_auto_20200428_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPurBeurre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_fr', models.CharField(max_length=155, unique=True)),
                ('generic_name_fr', models.CharField(max_length=400)),
                ('nutriscore', models.CharField(max_length=1)),
                ('nut_cent_gr', models.IntegerField()),
                ('link_off', models.URLField()),
                ('link_img', models.URLField()),
                ('category_s1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=150, unique=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.FoodPurBeurre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
