# Generated by Django 3.0.5 on 2020-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0006_favoris_foodpurbeurre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpurbeurre',
            name='product_name_fr',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
