# Generated by Django 3.0.5 on 2020-04-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0007_auto_20200429_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpurbeurre',
            name='link_img',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='foodpurbeurre',
            name='link_off',
            field=models.URLField(max_length=300),
        ),
    ]
