# Generated by Django 3.0.5 on 2020-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0008_auto_20200429_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpurbeurre',
            name='store',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
