# Generated by Django 3.0.5 on 2020-05-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0009_foodpurbeurre_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoris',
            name='search',
        ),
    ]
