# Generated by Django 3.0.5 on 2020-05-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purbeurre', '0011_auto_20200524_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoris',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purbeurre.FoodPurBeurre'),
        ),
    ]
